import { Inter } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`min-h-screen bg-background font-sans antialiased ${inter.className}`}>
        <div className="flex flex-col min-h-screen">
          <header className="px-4 py-3 border-b lg:px-6">
            <div className="container flex items-center gap-4 px-0 mx-auto">
              <a className="flex items-center gap-2" href="/">
                <span className="font-semibold">Legends League</span>
              </a>
            </div>
          </header>
          <main className="flex-1">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
